#!/bin/bash
srcdir=$1
target=$2

echo $target
echo $srcdir

build_game()
{
    cd $srcdir/game_server
    echo "build game_server ...."
    go build
    go install
    cd ..
}
build_log()
{
    cd $srcdir/log_server
    echo "build log_server ...."
    go build
    go install
    cd ..
}
build_db()
{
    cd $srcdir/db_server
    echo "build db_server ...."
    go build
    go install
    cd ..
}
build_mysql()
{
    cd $srcdir/mysql
    echo "build mysql ...."
    go build
    go install
    cd ..
}

build_all()
{
    build_game
    #build_log
    #build_db
    build_mysql
}

build()
{
    case $target in
        game)
            build_game
            ;;
        log)
            build_log
            ;;
        db)
            build_db
            ;;
        mysql)
            build_mysql
            ;;
        *)
            build_all
        exit
    esac
}

set +x
build
set -x

