// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	RequestUserVerify
	ReplyUserVerify
	Craft
	UploadNewCraft
	UploadNewCraftRet
	GetCraft
	GetCraftRet
	PraiseCraft
	PraiseCraftRet
	PraiseEntry
	GetPraiseMsg
	GetPraiseMsgRet
	Msg
*/
package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

// 新用户验证请求
type RequestUserVerify struct {
	Msgid            *int32 `protobuf:"varint,1,opt,name=msgid" json:"msgid,omitempty"`
	Userid           *int32 `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestUserVerify) Reset()         { *m = RequestUserVerify{} }
func (m *RequestUserVerify) String() string { return proto1.CompactTextString(m) }
func (*RequestUserVerify) ProtoMessage()    {}

func (m *RequestUserVerify) GetMsgid() int32 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *RequestUserVerify) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

// 新用户验证返回
type ReplyUserVerify struct {
	Msgid            *int32 `protobuf:"varint,1,opt,name=msgid" json:"msgid,omitempty"`
	Userid           *int32 `protobuf:"varint,2,opt,name=userid" json:"userid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReplyUserVerify) Reset()         { *m = ReplyUserVerify{} }
func (m *ReplyUserVerify) String() string { return proto1.CompactTextString(m) }
func (*ReplyUserVerify) ProtoMessage()    {}

func (m *ReplyUserVerify) GetMsgid() int32 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return 0
}

func (m *ReplyUserVerify) GetUserid() int32 {
	if m != nil && m.Userid != nil {
		return *m.Userid
	}
	return 0
}

// 关卡结构
type Craft struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Rect             *int32  `protobuf:"varint,2,opt,name=rect" json:"rect,omitempty"`
	Data             *string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Praise           *int32  `protobuf:"varint,4,opt,name=praise" json:"praise,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Craft) Reset()         { *m = Craft{} }
func (m *Craft) String() string { return proto1.CompactTextString(m) }
func (*Craft) ProtoMessage()    {}

func (m *Craft) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Craft) GetRect() int32 {
	if m != nil && m.Rect != nil {
		return *m.Rect
	}
	return 0
}

func (m *Craft) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

func (m *Craft) GetPraise() int32 {
	if m != nil && m.Praise != nil {
		return *m.Praise
	}
	return 0
}

// 上传新关卡
type UploadNewCraft struct {
	Typ              *int32 `protobuf:"varint,1,opt,name=typ" json:"typ,omitempty"`
	Craft            *Craft `protobuf:"bytes,2,opt,name=craft" json:"craft,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadNewCraft) Reset()         { *m = UploadNewCraft{} }
func (m *UploadNewCraft) String() string { return proto1.CompactTextString(m) }
func (*UploadNewCraft) ProtoMessage()    {}

func (m *UploadNewCraft) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *UploadNewCraft) GetCraft() *Craft {
	if m != nil {
		return m.Craft
	}
	return nil
}

// 上传新关卡返回
type UploadNewCraftRet struct {
	Ret              *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Craftid          *int32 `protobuf:"varint,2,opt,name=craftid" json:"craftid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UploadNewCraftRet) Reset()         { *m = UploadNewCraftRet{} }
func (m *UploadNewCraftRet) String() string { return proto1.CompactTextString(m) }
func (*UploadNewCraftRet) ProtoMessage()    {}

func (m *UploadNewCraftRet) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *UploadNewCraftRet) GetCraftid() int32 {
	if m != nil && m.Craftid != nil {
		return *m.Craftid
	}
	return 0
}

// 拉取关卡
type GetCraft struct {
	Typ              *int32 `protobuf:"varint,1,opt,name=typ" json:"typ,omitempty"`
	Idx              *int32 `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetCraft) Reset()         { *m = GetCraft{} }
func (m *GetCraft) String() string { return proto1.CompactTextString(m) }
func (*GetCraft) ProtoMessage()    {}

func (m *GetCraft) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *GetCraft) GetIdx() int32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

// 拉取关卡返回
type GetCraftRet struct {
	Ret              *int32   `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Crafts           []*Craft `protobuf:"bytes,2,rep,name=crafts" json:"crafts,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetCraftRet) Reset()         { *m = GetCraftRet{} }
func (m *GetCraftRet) String() string { return proto1.CompactTextString(m) }
func (*GetCraftRet) ProtoMessage()    {}

func (m *GetCraftRet) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *GetCraftRet) GetCrafts() []*Craft {
	if m != nil {
		return m.Crafts
	}
	return nil
}

// 点赞
type PraiseCraft struct {
	Typ              *int32 `protobuf:"varint,1,opt,name=typ" json:"typ,omitempty"`
	Idx              *int32 `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`
	Id               *int32 `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PraiseCraft) Reset()         { *m = PraiseCraft{} }
func (m *PraiseCraft) String() string { return proto1.CompactTextString(m) }
func (*PraiseCraft) ProtoMessage()    {}

func (m *PraiseCraft) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *PraiseCraft) GetIdx() int32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

func (m *PraiseCraft) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 点赞返回
type PraiseCraftRet struct {
	Ret              *int32 `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PraiseCraftRet) Reset()         { *m = PraiseCraftRet{} }
func (m *PraiseCraftRet) String() string { return proto1.CompactTextString(m) }
func (*PraiseCraftRet) ProtoMessage()    {}

func (m *PraiseCraftRet) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

// 点赞结构
type PraiseEntry struct {
	Id               *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Praise           *int32 `protobuf:"varint,2,opt,name=praise" json:"praise,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PraiseEntry) Reset()         { *m = PraiseEntry{} }
func (m *PraiseEntry) String() string { return proto1.CompactTextString(m) }
func (*PraiseEntry) ProtoMessage()    {}

func (m *PraiseEntry) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *PraiseEntry) GetPraise() int32 {
	if m != nil && m.Praise != nil {
		return *m.Praise
	}
	return 0
}

// 拉取点赞
type GetPraiseMsg struct {
	Typ              *int32 `protobuf:"varint,1,opt,name=typ" json:"typ,omitempty"`
	Idx              *int32 `protobuf:"varint,2,opt,name=idx" json:"idx,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetPraiseMsg) Reset()         { *m = GetPraiseMsg{} }
func (m *GetPraiseMsg) String() string { return proto1.CompactTextString(m) }
func (*GetPraiseMsg) ProtoMessage()    {}

func (m *GetPraiseMsg) GetTyp() int32 {
	if m != nil && m.Typ != nil {
		return *m.Typ
	}
	return 0
}

func (m *GetPraiseMsg) GetIdx() int32 {
	if m != nil && m.Idx != nil {
		return *m.Idx
	}
	return 0
}

// 拉取点赞返回
type GetPraiseMsgRet struct {
	Ret              *int32         `protobuf:"varint,1,opt,name=ret" json:"ret,omitempty"`
	Praises          []*PraiseEntry `protobuf:"bytes,2,rep,name=praises" json:"praises,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GetPraiseMsgRet) Reset()         { *m = GetPraiseMsgRet{} }
func (m *GetPraiseMsgRet) String() string { return proto1.CompactTextString(m) }
func (*GetPraiseMsgRet) ProtoMessage()    {}

func (m *GetPraiseMsgRet) GetRet() int32 {
	if m != nil && m.Ret != nil {
		return *m.Ret
	}
	return 0
}

func (m *GetPraiseMsgRet) GetPraises() []*PraiseEntry {
	if m != nil {
		return m.Praises
	}
	return nil
}

// 暂时不用,后续会设计一个统一消息处理的机制
type Msg struct {
	// required int32              msgid   = 1;
	ReqUv            *RequestUserVerify `protobuf:"bytes,2,opt,name=req_uv" json:"req_uv,omitempty"`
	RepUv            *ReplyUserVerify   `protobuf:"bytes,3,opt,name=rep_uv" json:"rep_uv,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Msg) Reset()         { *m = Msg{} }
func (m *Msg) String() string { return proto1.CompactTextString(m) }
func (*Msg) ProtoMessage()    {}

func (m *Msg) GetReqUv() *RequestUserVerify {
	if m != nil {
		return m.ReqUv
	}
	return nil
}

func (m *Msg) GetRepUv() *ReplyUserVerify {
	if m != nil {
		return m.RepUv
	}
	return nil
}

func init() {
}
